// Sitemap proxy/rewrite — replaces the standalone sitemap service.
//
// GET /sitemap_index.xml         -> fetch the API's SitemapIndex for this host's
//                                   shortcode and rewrite each child <loc> to a
//                                   public https://<host>/sitemap/sitemap-<n>.xml.
// GET /sitemap/sitemap-<n>.xml    -> fetch the n-th child URL from that index
//                                   (verbatim, XML-unescaped) and pass it through.
//
// It's a fetch + XML-rewrite proxy (no headless render), public (mounted as Express
// routes before the catch-all, so it bypasses tokenAuth/whitelist). Only the index
// is rewritten; per-page sitemaps already contain public URLs and are passed
// through unchanged.
//
// Caching: the API's SitemapIndex + per-page sitemaps are generated by a heavy DB
// query, so both the index and each sub-sitemap are cached in Redis with a TTL
// (SITEMAP_CACHE_TTL_MS, default 6h), single-flight (only ONE request regenerates
// a cold/expired entry — the rest serve the existing copy or wait), and
// serve-stale-on-error (a DB/API hiccup returns the last good copy instead of
// hammering the origin). With no Redis configured it degrades to a direct fetch
// (the original behavior).
const http = require('http');
const https = require('https');
const crypto = require('crypto');
const { URL } = require('url');
const util = require('./util.js');

// Compare-and-delete: release the single-flight lock only if we still own it.
const RELEASE_LUA =
  "if redis.call('get', KEYS[1]) == ARGV[1] then return redis.call('del', KEYS[1]) else return 0 end";

function parseConfig() {
  const map = {}; // host -> code
  const byCode = {}; // code -> canonical host (first wins) — for rewriting the index
  (process.env.SITEMAP_SHORTCODES || 'chicksx.com:CX,chicksgold.com:CG')
    .split(',')
    .forEach((pair) => {
      const idx = pair.indexOf(':');
      if (idx < 0) return;
      const host = pair.slice(0, idx).trim().toLowerCase();
      const code = pair.slice(idx + 1).trim();
      if (host && code) {
        map[host] = code;
        if (!byCode[code]) byCode[code] = host;
      }
    });
  const apiBase = (
    process.env.SITEMAP_API_BASE || 'https://api.chicksgroup.com'
  ).replace(/\/+$/, '');
  return {
    enabled: (process.env.SITEMAP_PROXY_ENABLED || 'false') === 'true',
    apiBase,
    // Per-environment API origins. The fork is shared across envs, so dev/staging
    // sitemaps must pull from the matching API (and rewrite to the dev./staging.
    // host) — nginx tells us which via the X-Environment header.
    apiBaseByEnv: {
      prod: apiBase,
      dev: (
        process.env.SITEMAP_API_BASE_DEV || 'https://dev-api.chicksgroup.com'
      ).replace(/\/+$/, ''),
      staging: (
        process.env.SITEMAP_API_BASE_STAGING ||
        'https://staging-api.chicksgroup.com'
      ).replace(/\/+$/, ''),
    },
    shortcodes: map,
    hostByCode: byCode,
    timeoutMs: parseInt(process.env.SITEMAP_TIMEOUT_MS || '15000', 10),
    // Redis cache for the upstream API sitemap fetches (index + sub-sitemaps).
    // 0 disables caching (direct fetch every time). staleTtl keeps an expired
    // copy around for serve-stale-on-error; waitMax bounds how long a cold-start
    // waiter blocks for the single-flight holder before failing closed.
    cacheTtlMs: parseInt(process.env.SITEMAP_CACHE_TTL_MS || '21600000', 10), // 6h
    cacheStaleTtlMs: parseInt(
      process.env.SITEMAP_CACHE_STALE_TTL_MS || '86400000',
      10,
    ), // 24h
    cacheWaitMaxMs: parseInt(process.env.SITEMAP_CACHE_WAIT_MS || '15000', 10),
    cacheKeyPrefix: process.env.CACHE_KEY_PREFIX || 'prerender',
  };
}

// Public-host prefix per environment, so dev/staging sitemaps point at the right
// subdomain (dev.chicksx.com / staging.chicksx.com) instead of the apex.
const ENV_HOST_PREFIX = { prod: '', dev: 'dev.', staging: 'staging.' };

let config = parseConfig();
let fetchFn = null; // set to fetchText below; injectable for tests

function enabled() {
  return config.enabled;
}

// Canonical apex host: lowercase, no port/path, no leading www.
function normHost(host) {
  let h = (host || '').toLowerCase().trim();
  h = h.split('/')[0].split(':')[0];
  if (h.startsWith('www.')) h = h.slice(4);
  return h;
}

function shortcodeFor(host) {
  return config.shortcodes[normHost(host)] || null;
}

// Which environment this request is for (dev/staging/prod). nginx sends
// X-Environment per server block; defaults to prod.
function envOf(req) {
  const raw =
    (req && req.headers && req.headers['x-environment']) ||
    (req && req.query && req.query.env) ||
    '';
  const e = String(raw).trim().toLowerCase();
  if (e === 'dev' || e === 'development') return 'dev';
  if (e === 'staging' || e === 'stage') return 'staging';
  return 'prod';
}

// Resolve { code, host, apiBase, env } for a request. An explicit code from the
// front proxy (X-Website-Code header or ?websiteCode= query) wins — so this works
// regardless of the Host the proxy forwards — with the public host reverse-mapped
// from the code and prefixed for the environment (dev./staging.), used to rewrite
// the index <loc>s. The API origin is chosen per environment too. Falls back to
// the Host map for direct access. Returns null when no site can be determined.
function resolveSite(req) {
  const env = envOf(req);
  const apiBase = config.apiBaseByEnv[env] || config.apiBase;
  const prefix = ENV_HOST_PREFIX[env] || '';
  const hdr = req && req.headers ? req.headers['x-website-code'] : '';
  const q = req && req.query ? req.query.websiteCode : '';
  const explicit = String(hdr || q || '').trim();
  if (explicit && /^[A-Za-z0-9]{1,16}$/.test(explicit)) {
    const apex = config.hostByCode[explicit] || normHost(hostOf(req));
    return { code: explicit, host: prefix + apex, apiBase, env };
  }
  const apex = normHost(hostOf(req));
  const code = config.shortcodes[apex];
  return code ? { code: code, host: prefix + apex, apiBase, env } : null;
}

function xmlUnescape(s) {
  return String(s)
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&#(\d+);/g, (_, d) => String.fromCharCode(parseInt(d, 10)))
    .replace(/&amp;/g, '&'); // ampersand last so &amp;lt; -> &lt;
}

function xmlEscape(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

// Ordered list of { loc, lastmod } from a <sitemapindex>. Sitemaps are simple,
// well-formed XML, so a tolerant regex pass is enough (no XML dep).
function parseSitemapLocs(xml) {
  const out = [];
  const blockRe = /<sitemap\b[^>]*>([\s\S]*?)<\/sitemap>/gi;
  let m;
  while ((m = blockRe.exec(xml)) !== null) {
    const block = m[1];
    const loc = /<loc>\s*([\s\S]*?)\s*<\/loc>/i.exec(block);
    if (!loc) continue;
    const lm = /<lastmod>\s*([\s\S]*?)\s*<\/lastmod>/i.exec(block);
    out.push({
      loc: xmlUnescape(loc[1].trim()),
      lastmod: lm ? lm[1].trim() : null,
    });
  }
  return out;
}

// Rebuild a clean <sitemapindex> pointing children at our public per-page URLs.
function renderIndex(host, entries) {
  const items = entries.map((e, i) => {
    const loc = `https://${host}/sitemap/sitemap-${i + 1}.xml`;
    const lm = e.lastmod
      ? `\n    <lastmod>${xmlEscape(e.lastmod)}</lastmod>`
      : '';
    return `  <sitemap>\n    <loc>${xmlEscape(loc)}</loc>${lm}\n  </sitemap>`;
  });
  return (
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
    items.join('\n') +
    '\n</sitemapindex>\n'
  );
}

// GET an XML resource as text. Non-2xx / timeout / network error -> reject.
function fetchText(url) {
  return new Promise((resolve, reject) => {
    let u;
    try {
      u = new URL(url);
    } catch (e) {
      return reject(new Error('bad sitemap url'));
    }
    const lib = u.protocol === 'http:' ? http : https;
    const req = lib.request(
      url,
      {
        method: 'GET',
        headers: {
          Accept: 'application/xml,text/xml,*/*',
          'Accept-Encoding': 'identity',
          'User-Agent': 'ChicksPrerenderSitemapProxy/1.0',
        },
      },
      (res) => {
        if (res.statusCode < 200 || res.statusCode >= 300) {
          res.resume();
          return reject(new Error('upstream HTTP ' + res.statusCode));
        }
        const chunks = [];
        res.on('data', (c) => chunks.push(c));
        res.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
        res.on('error', reject);
      },
    );
    req.setTimeout(config.timeoutMs, () =>
      req.destroy(new Error('sitemap fetch timeout')),
    );
    req.on('error', reject);
    req.end();
  });
}
fetchFn = fetchText;

// --- sitemap cache (Redis, best-effort) ------------------------------------
let cacheClient = null; // ioredis client (lazy) or test-injected
let cacheClientTried = false;
let cacheNow = () => Date.now(); // injectable clock for tests

function redisConfigured() {
  return !!(process.env.REDIS_URL || process.env.REDIS_HOST);
}

// Dedicated ioredis client. The sitemap routes bypass the plugin pipeline, so we
// can't rely on redisCache's lazily-initialized client. Mirrors its fail-fast
// options so a Redis outage degrades to a direct fetch rather than hanging.
function getCacheClient() {
  if (cacheClient || cacheClientTried) return cacheClient;
  cacheClientTried = true;
  if (!redisConfigured()) return null;
  try {
    const Redis = require('ioredis');
    const opts = {
      lazyConnect: true,
      enableOfflineQueue: false,
      maxRetriesPerRequest: 1,
      connectTimeout: 3000,
      reconnectOnError: () => false,
      retryStrategy: (t) => Math.min(t * 200, 2000),
    };
    cacheClient = process.env.REDIS_URL
      ? new Redis(process.env.REDIS_URL, opts)
      : new Redis(
          Object.assign({}, opts, {
            host: process.env.REDIS_HOST || '127.0.0.1',
            port: parseInt(process.env.REDIS_PORT || '6379', 10),
            password: process.env.REDIS_PASSWORD || undefined,
            tls: process.env.REDIS_TLS === 'true' ? {} : undefined,
          }),
        );
    cacheClient.on('error', (e) =>
      util.log('[sitemap] redis error', e && e.message),
    );
    cacheClient.connect().catch(() => {});
  } catch (e) {
    cacheClient = null;
  }
  return cacheClient;
}

function cacheEnabled() {
  return config.cacheTtlMs > 0 && !!getCacheClient();
}

function smHash(url) {
  return crypto.createHash('sha1').update(String(url)).digest('hex');
}
function smKey(url) {
  return `${config.cacheKeyPrefix}:v1:sitemap:${smHash(url)}`;
}
function smLockKey(url) {
  return `${config.cacheKeyPrefix}:v1:sitemaplock:${smHash(url)}`;
}

function readStored(client, key) {
  return Promise.resolve()
    .then(() => client.get(key))
    .then((raw) => {
      if (!raw) return null;
      try {
        const o = JSON.parse(raw);
        if (o && typeof o.b === 'string' && typeof o.at === 'number') return o;
      } catch (e) {
        /* ignore malformed */
      }
      return null;
    })
    .catch(() => null);
}

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

// Fetch an API sitemap URL through the cache. Fresh hit -> cached copy;
// cold/expired -> single-flight regeneration (others serve the prior copy or
// wait); fetch error -> serve the last good copy if we have one. Degrades to a
// direct fetch when caching is disabled / Redis is unreachable.
function cachedFetch(url) {
  if (!cacheEnabled()) return fetchFn(url);
  const client = getCacheClient();
  const key = smKey(url);
  const lockKey = smLockKey(url);
  const lockTtlMs = config.timeoutMs + 5000;

  return readStored(client, key).then((stored) => {
    if (stored && cacheNow() - stored.at < config.cacheTtlMs) {
      return stored.b; // fresh
    }
    const token = `${process.pid}-${cacheNow()}-${Math.random().toString(36).slice(2)}`;
    return Promise.resolve()
      .then(() => client.set(lockKey, token, 'PX', lockTtlMs, 'NX'))
      .catch(() => null)
      .then((lockRes) => {
        if (lockRes === 'OK') {
          // We own the regeneration: fetch, store, release.
          const release = () =>
            Promise.resolve()
              .then(() => client.eval(RELEASE_LUA, 1, lockKey, token))
              .catch(() => {});
          return Promise.resolve()
            .then(() => fetchFn(url))
            .then((body) =>
              Promise.resolve()
                .then(() =>
                  client.set(
                    key,
                    JSON.stringify({ b: body, at: cacheNow() }),
                    'PX',
                    config.cacheStaleTtlMs,
                  ),
                )
                .catch(() => {})
                .then(() => body),
            )
            .catch((err) => {
              if (stored) {
                util.log(
                  '[sitemap] serving stale after fetch error',
                  url,
                  err && err.message,
                );
                return stored.b; // serve-stale-on-error
              }
              throw err;
            })
            .then(
              (v) => release().then(() => v),
              (e) => release().then(() => Promise.reject(e)),
            );
        }
        // Another worker is regenerating.
        if (stored) return stored.b; // serve slightly-stale now, no origin hit
        // Cold start + contention: wait for the holder, don't pile onto the origin.
        const deadline = cacheNow() + config.cacheWaitMaxMs;
        const poll = () => {
          if (cacheNow() >= deadline) {
            throw new Error('sitemap cache wait timeout');
          }
          return sleep(250)
            .then(() => readStored(client, key))
            .then((s) => (s ? s.b : poll()));
        };
        return poll();
      });
  });
}

function indexApiUrl(apiBase, code) {
  return `${apiBase}/Sitemap/SitemapIndex?websiteShortCode=${encodeURIComponent(code)}`;
}

function sendXml(res, body) {
  res.setHeader('Content-Type', 'application/xml; charset=utf-8');
  res.status(200).send(body);
}

function hostOf(req) {
  if (req.hostname) return req.hostname;
  const h = req.headers && req.headers.host ? req.headers.host : '';
  return h.split(':')[0];
}

// GET /sitemap_index.xml
function index(req, res) {
  const site = resolveSite(req);
  if (!site) return res.sendStatus(404);
  return Promise.resolve()
    .then(() => cachedFetch(indexApiUrl(site.apiBase, site.code)))
    .then((xml) => sendXml(res, renderIndex(site.host, parseSitemapLocs(xml))))
    .catch((e) => {
      util.log('[sitemap] index error', site.env, site.code, e && e.message);
      return res.sendStatus(502);
    });
}

// GET /sitemap/sitemap-<n>.xml
function page(req, res, n) {
  const site = resolveSite(req);
  if (!site) return res.sendStatus(404);
  if (!Number.isInteger(n) || n < 1) return res.sendStatus(404);
  return Promise.resolve()
    .then(() => cachedFetch(indexApiUrl(site.apiBase, site.code)))
    .then((xml) => {
      const entries = parseSitemapLocs(xml);
      if (n > entries.length) return res.sendStatus(404);
      return cachedFetch(entries[n - 1].loc).then((body) => sendXml(res, body));
    })
    .catch((e) => {
      util.log('[sitemap] page error', site.env, site.code, n, e && e.message);
      return res.sendStatus(502);
    });
}

module.exports = {
  enabled,
  index,
  page,
  // exposed for tests / reuse
  shortcodeFor,
  parseSitemapLocs,
  renderIndex,
  // --- test seams ---
  _setFetchForTests: (fn) => {
    fetchFn = fn || fetchText;
  },
  _setConfigForTests: (overrides) => {
    config = Object.assign(parseConfig(), overrides || {});
  },
  _setCacheForTests: (opts) => {
    opts = opts || {};
    cacheClient = opts.client || null;
    cacheClientTried = true; // skip the real builder
    cacheNow = opts.now || (() => Date.now());
  },
  _cachedFetch: cachedFetch,
};
